### PR TITLE
Fix #78: ignore hyphenated file|directory name

### LINKED ISSUE #78: ignore option does not work with "dist-newstyle"
Hi,
The ignore option does not work with a folder named "dist-newstyle", it does work with folders with different names.

### PR DESCRIPTION
**Pull request by Pheon-Dev**
Fixing issue #78

### CODE REVIEW

**Comment by tamago324** [comment]
Thanks for giving me the PR.
I think I can make it shorter if I use `vim.pesc()`. What do you think?

> `:help vim.pesc`
> 
> ```vim
> pesc({s})                                                         *vim.pesc()*
>     Escapes magic chars in |lua-patterns|.
> 
>     Parameters:  
>       • {s}  (string) String to escape
> 
>     Return:  
>         (string) %-escaped pattern string
> 
>     See also:  
>         https://github.com/rxi/lume
> ```

Also, I think that an exact match, not a forward match, is just the way to go, so I think the following would work, how about that?


```diff
diff --git a/lua/lir.lua b/lua/lir.lua
index 960e8cb..eccc00c 100644
--- a/lua/lir.lua
+++ b/lua/lir.lua
@@ -214,8 +214,7 @@ function lir.init()
       return
     end
     files = vim.tbl_filter(function(val)
-      local f = "^" .. file .. ".-$"
-      return string.match(val.value, f) == nil
+      return string.match(val.value, vim.pesc(file)) == nil
     end, files)
   end
```

**Comment by Pheon-Dev** [comment]
Thats totally fine

**Comment by tamago324** [comment]
I'm sorry.
I don't think you can determine it correctly that way.

To begin with, the `ignore` option is a literal comparison, right?
Then I guess you could use equal (`==`) comparisons instead of `string.match`.

**Comment by Pheon-Dev** [comment]
> I'm sorry. I don't think you can determine it correctly that way.
> 
> To begin with, the `ignore` option is a literal comparison, right? Then I guess you could use equal (`==`) comparisons instead of `string.match`.

Thanks for the insight, just did as you suggested(or rather suggestively asked) and it just worked like magic.

**Comment by tamago324** [comment]
It could be written shorter to filter out those that do not match `config.values.ignore`.

```diff
diff --git a/lua/lir.lua b/lua/lir.lua
index 7f2f237..40a3e1f 100644
--- a/lua/lir.lua
+++ b/lua/lir.lua
@@ -209,17 +209,9 @@ function lir.init()
     end, files)
   end
 
-  for _, file in pairs(config.values.ignore) do
-    if file == nil then
-      return
-    end
-    files = vim.tbl_filter(function(val)
-      if val.value == file then
-        return nil
-      end
-      return val.value
-    end, files)
-  end
+  files = vim.tbl_filter(function(val)
+    return not vim.tbl_contains(config.values.ignore, val.value)
+  end, files)
 
   table.sort(files, sort)
```

**Comment by Pheon-Dev** [comment]
> It could be written shorter to filter out those that do not match `config.values.ignore`.
> 
> 
> 
> ```diff
> 
> diff --git a/lua/lir.lua b/lua/lir.lua
> 
> index 7f2f237..40a3e1f 100644
> 
> --- a/lua/lir.lua
> 
> +++ b/lua/lir.lua
> 
> @@ -209,17 +209,9 @@ function lir.init()
> 
>      end, files)
> 
>    end
> 
>  
> 
> -  for _, file in pairs(config.values.ignore) do
> 
> -    if file == nil then
> 
> -      return
> 
> -    end
> 
> -    files = vim.tbl_filter(function(val)
> 
> -      if val.value == file then
> 
> -        return nil
> 
> -      end
> 
> -      return val.value
> 
> -    end, files)
> 
> -  end
> 
> +  files = vim.tbl_filter(function(val)
> 
> +    return not vim.tbl_contains(config.values.ignore, val.value)
> 
> +  end, files)
> 
>  
> 
>    table.sort(files, sort)
> 
> ```

Even better. Just did the necessary changes.

**Review by tamago324 — APPROVED** [review]
LGTM

**Pull request merged**
